# Generated by Django 6.0.7 on 2026-07-30 10:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sport', models.CharField(default='badminton_single_game', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='tournaments.tournament')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tournament', 'name'), name='uniq_court_name')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('draw_format', models.CharField(choices=[('knockout', 'Knockout'), ('round_robin', 'Round Robin')], default='knockout', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('draw_generated', 'Draw Generated'), ('locked', 'Locked')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tournaments.tournament')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'constraints': [models.UniqueConstraint(fields=('tournament', 'name'), name='uniq_category_name')],
            },
        ),
    ]
