# Generated by Django 6.0.7 on 2026-07-31 14:19

from django.db import migrations


def fix_missing_tournament_roles(apps, schema_editor):
    """Assign organization owners as organizers for existing tournaments."""
    Tournament = apps.get_model('tournaments', 'Tournament')
    TournamentRole = apps.get_model('accounts', 'TournamentRole')
    
    for tournament in Tournament.objects.all():
        org_owner = tournament.organization.owner
        TournamentRole.objects.get_or_create(
            user=org_owner,
            tournament=tournament,
            defaults={
                'role': 'organizer',
                'is_active': True,
                'granted_by': org_owner,
            }
        )


def reverseMigration(apps, schema_editor):
    """No need to reverse data fixes."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fix_missing_tournament_roles, reverseMigration),
    ]
