# Generated by Django 6.0.7 on 2026-07-31 12:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('draws', '0001_initial'),
        ('entries', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.PositiveIntegerField()),
                ('slot_position', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('bye', 'Bye')], default='pending', max_length=20)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('score', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=0)),
                ('next_match_slot', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.category')),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournaments.court')),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='draws.draw')),
                ('entry1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_p1', to='entries.entry')),
                ('entry2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_p2', to='entries.entry')),
                ('next_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeder_matches', to='matches.match')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
                ('winner_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='entries.entry')),
            ],
            options={
                'indexes': [models.Index(fields=['tournament', 'category', 'status'], name='matches_mat_tournam_71c747_idx'), models.Index(fields=['court', 'scheduled_start'], name='matches_mat_court_i_1bd3d5_idx'), models.Index(fields=['tournament', 'status', 'scheduled_start'], name='matches_mat_tournam_43c522_idx')],
            },
        ),
    ]
