# Generated by Django 6.0.7 on 2026-07-30 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentrole',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='tournamentrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assistantcapability',
            name='tournament_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='accounts.tournamentrole'),
        ),
        migrations.AddIndex(
            model_name='tournamentrole',
            index=models.Index(fields=['tournament', 'role', 'is_active'], name='accounts_to_tournam_f35f6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='tournamentrole',
            constraint=models.UniqueConstraint(fields=('user', 'tournament', 'role'), name='uniq_user_tournament_role'),
        ),
        migrations.AddConstraint(
            model_name='assistantcapability',
            constraint=models.UniqueConstraint(fields=('tournament_role', 'capability'), name='uniq_role_capability'),
        ),
    ]
