# Generated by Django 6.0.7 on 2026-07-30 10:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('withdrawn', 'Withdrawn'), ('refunded', 'Refunded'), ('waitlist', 'Waitlist')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tournaments.category')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounts.playerprofile')),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'indexes': [models.Index(fields=['category', 'status'], name='entries_ent_categor_b50dd3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('category', 'player'), name='uniq_active_entry_per_category')],
            },
        ),
    ]
