# Generated by Django 6.0.7 on 2026-07-30 10:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entries', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('finalized', 'Finalized'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('version', models.PositiveIntegerField(default=0)),
                ('fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draw', to='tournaments.category')),
            ],
        ),
        migrations.CreateModel(
            name='DrawSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveIntegerField()),
                ('is_bye', models.BooleanField(default=False)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='draws.draw')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draw_slots', to='entries.entry')),
            ],
            options={
                'ordering': ['round_number', 'position'],
                'constraints': [models.UniqueConstraint(fields=('draw', 'round_number', 'position'), name='uniq_draw_slot_position')],
            },
        ),
    ]
